export interface Book {
  /** Stable identifier generated by the app. */
  id: string;
  title: string;
  authors: string[];
  /** Open Library work key, e.g. "/works/OL45804W". Empty for manually entered books. */
  olKey: string;
  /** Open Library cover id (covers.openlibrary.org/b/id/{coverId}-M.jpg). */
  coverId: number | null;
  firstPublishYear: number | null;
  /** 0-10 in 0.5 steps. */
  rating: number;
  review: string;
  tags: string[];
  /** ISO date (yyyy-mm-dd) or empty. */
  dateRead: string;
  createdAt: string;
  updatedAt: string;
}

export type BookDraft = Omit<Book, 'id' | 'createdAt' | 'updatedAt'>;

export interface UserProfile {
  email: string;
  name: string;
  picture: string;
}

export type SortKey = 'recent' | 'ratingDesc' | 'ratingAsc' | 'title' | 'dateRead';

export interface BookFilter {
  text: string;
  minRating: number;
  maxRating: number;
  tags: string[];
  tagMode: 'any' | 'all';
  sort: SortKey;
}
